from django.urls import path, re_path
from . import views
urlpatterns = [
    path('login', views.LoginAPIView.as_view()),
    path('login/mobile', views.LoginMobileAPIView.as_view()),
    path('register', views.RegisterAPIView.as_view()),
    path('sms', views.SMSAPIView.as_view()),
    path('mobile', views.MobileAPIView.as_view()),
    path('email', views.EmailAPIView.as_view()),
    path('avatar', views.AvatarListAPIView.as_view()),
    path('userdetail', views.UserdetailsAPIView.as_view()),
    path('articles', views.ArticlesAPIView.as_view()),
    path('art_list', views.ArtlistAPIView.as_view()),
    path('article', views.ArticleAPIView.as_view()),
    path('comment_list', views.Comment_listAPIView.as_view()),
    path('comment', views.CommentAPIView.as_view()),
    path('classarticle', views.ClassarticleAPIView.as_view()),
    path('informations', views.InformationsAPIView.as_view()),
    path('category', views.CategoryAPIView.as_view()),
    path('pictures', views.PictureAPIView.as_view()),
    path('tag', views.TagAPIView.as_view()),
    path('categorys', views.CategorysAPIView.as_view()),
    path('categoryss', views.CategoryssAPIView.as_view()),
    path('category_list', views.CategorylistAPIView.as_view()),
    path('article_list', views.ArticlelistAPIView.as_view()),
    path('articles_list', views.ArticleslistAPIView.as_view()),
    path('query', views.QueryAPIView.as_view()),
    path('tags', views.TagsAPIView.as_view()),
    path('background', views.BackgroundAPIView.as_view()),
    path('changeinformation', views.ChangeinformationAPIView.as_view()),
]